### PR TITLE
Remove NITE as a system dependency

### PR DESCRIPTION
**Pull request by adwilson10**
This PR addresses issues #6 and #7 since NITE is technically not allowed to be repackaged anymore.  Openni_tracker does not need to be linked to NITE libraries, so having users manually post-install NITE works fine.  When NITE is not installed, an error message directs users to the README for download locations.  This should also allow release into Indigo which doesn't provide libopenni-nite-dev.

### CODE REVIEW

**Comment by wjwwood** [comment]
@adwilson10 sorry I haven't had time to look at this, the other maintainers are quite busy right now too I believe. But we'll get to it eventually, I just wanted to let you know we hadn't forgotten about this.

**Comment by bit-pirate** [comment]
Looks good at first glance, but haven't had the chance to test it myself. Will try get myself or someone on the lab to test it soon.

**Comment by bit-pirate** [comment]
Just checked it. I think this is a good addition!

**Comment by bit-pirate** [comment]
This should also allow us to release this package for both hydro and indigo. Merging now.

Thanks for the contribution @adwilson10 !

**Pull request merged**
